# Generated by Django 5.1 on 2025-10-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products_calisthenics',
        ),
    ]
