# Generated by Django 5.1 on 2025-10-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Paralleltes', 'PARALLETTES'), ('Accessories', 'ACCESSORIES')], default='Paralleltes', max_length=100),
        ),
    ]
